window.esdocSearchIndex = [
  [
    "gigya-api-wrapper/src/index.js~gigyawrapper",
    "class/src/index.js~GigyaWrapper.html",
    "<span>GigyaWrapper</span> <span class=\"search-result-import-path\">gigya-api-wrapper/src/index.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~gigyawrapper#apikey",
    "class/src/index.js~GigyaWrapper.html#instance-member-apiKey",
    "src/index.js~GigyaWrapper#apiKey",
    "member"
  ],
  [
    "src/index.js~gigyawrapper#autologin",
    "class/src/index.js~GigyaWrapper.html#instance-member-autoLogin",
    "src/index.js~GigyaWrapper#autoLogin",
    "member"
  ],
  [
    "src/index.js~gigyawrapper#cb",
    "class/src/index.js~GigyaWrapper.html#instance-method-cb",
    "src/index.js~GigyaWrapper#cb",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#checkloggedinstatus",
    "class/src/index.js~GigyaWrapper.html#instance-method-checkLoggedInStatus",
    "src/index.js~GigyaWrapper#checkLoggedInStatus",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#constructor",
    "class/src/index.js~GigyaWrapper.html#instance-constructor-constructor",
    "src/index.js~GigyaWrapper#constructor",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#containerid",
    "class/src/index.js~GigyaWrapper.html#instance-member-containerID",
    "src/index.js~GigyaWrapper#containerID",
    "member"
  ],
  [
    "src/index.js~gigyawrapper#debug",
    "class/src/index.js~GigyaWrapper.html#instance-member-debug",
    "src/index.js~GigyaWrapper#debug",
    "member"
  ],
  [
    "src/index.js~gigyawrapper#getaccountinfo",
    "class/src/index.js~GigyaWrapper.html#instance-method-getAccountInfo",
    "src/index.js~GigyaWrapper#getAccountInfo",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#getpolicies",
    "class/src/index.js~GigyaWrapper.html#instance-method-getPolicies",
    "src/index.js~GigyaWrapper#getPolicies",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#getschema",
    "class/src/index.js~GigyaWrapper.html#instance-method-getSchema",
    "src/index.js~GigyaWrapper#getSchema",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#getscreensets",
    "class/src/index.js~GigyaWrapper.html#instance-method-getScreenSets",
    "src/index.js~GigyaWrapper#getScreenSets",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#gigya",
    "class/src/index.js~GigyaWrapper.html#instance-member-gigya",
    "src/index.js~GigyaWrapper#gigya",
    "member"
  ],
  [
    "src/index.js~gigyawrapper#hidescreenset",
    "class/src/index.js~GigyaWrapper.html#instance-method-hideScreenSet",
    "src/index.js~GigyaWrapper#hideScreenSet",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#lang",
    "class/src/index.js~GigyaWrapper.html#instance-member-lang",
    "src/index.js~GigyaWrapper#lang",
    "member"
  ],
  [
    "src/index.js~gigyawrapper#logout",
    "class/src/index.js~GigyaWrapper.html#instance-method-logout",
    "src/index.js~GigyaWrapper#logout",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#noop",
    "class/src/index.js~GigyaWrapper.html#instance-member-noop",
    "src/index.js~GigyaWrapper#noop",
    "member"
  ],
  [
    "src/index.js~gigyawrapper#onlibraryready",
    "class/src/index.js~GigyaWrapper.html#instance-method-onLibraryReady",
    "src/index.js~GigyaWrapper#onLibraryReady",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#registereventlisteners",
    "class/src/index.js~GigyaWrapper.html#instance-method-registerEventListeners",
    "src/index.js~GigyaWrapper#registerEventListeners",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#screenset",
    "class/src/index.js~GigyaWrapper.html#instance-member-screenSet",
    "src/index.js~GigyaWrapper#screenSet",
    "member"
  ],
  [
    "src/index.js~gigyawrapper#share",
    "class/src/index.js~GigyaWrapper.html#instance-method-share",
    "src/index.js~GigyaWrapper#share",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#showloginscreen",
    "class/src/index.js~GigyaWrapper.html#instance-method-showLoginScreen",
    "src/index.js~GigyaWrapper#showLoginScreen",
    "method"
  ],
  [
    "src/index.js~gigyawrapper#showscreenset",
    "class/src/index.js~GigyaWrapper.html#instance-method-showScreenSet",
    "src/index.js~GigyaWrapper#showScreenSet",
    "method"
  ]
]